### ISSUE TITLE
Possible to publish to any channel?

### ISSUE THREAD

**Issue by mo3rfan** [vovadenisov/centrifuge-python#5]
Is it possible for clients using this library to publish to an arbitrary channel?

According to the following, https://github.com/centrifugal/centrifuge-python/blob/1b0f3234aa748fb1dc1326ff54eb1ad98f5537d3/centrifuge/client.py#L404-L407
It seems like I can only publish something to a channel that the client has already subscribed. Is this feature not ready yet or should I just use https://github.com/centrifugal/cent

**Comment by FZambia** [comment]
Hi! That's by design - client can only publish into channel it subscribed to. And that channel must be in namespace with `"publish": true` set.

Using `cent` you can publish messages into all channels at any moment.

**Comment by mo3rfan** [comment]
Thanks for the quick reply! ~~Will this be on the roadmap for this project? I just don't understand the reason why `cent` supports it but this websockets library chose not to.~~

I think I should simply use `cent` and `centrifuge-python` together for my use case. `cent` for publishing to any channel and `centrifuge-python` for subscribing.

**Comment by FZambia** [comment]
> Will this be on the roadmap for this project? I just don't understand the reason why cent supports it but this websockets library chose not to.

Because Centrifugo designed to work in conjunction with app backend - message should first come to app backend and then be published to Centrifugo. If client publishes message into channel directly - then app backend never know about that message, it just goes through Centrifugo. 

Maybe this is not obvious for you because looks like you are using Centrifugo server-side, while most use Centrifugo for client-facing Javascript apps and need message validation/saving before broadcasting to all subscribers.
